import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import NextUILayout from "./NextUIProvider";
import NavbarComponent from "@/components/layouts/navbar/NavbarComponent";
import { Suspense } from "react";
import LoadingComponent from "./loading";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import Error from "./error";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: {
		template: "%s | Homepage",
		default: "Homepage",
	},
	description: "Generated by create next app",
	keywords: ["NextUI", "React", "Next.js"],
	openGraph: {
		title: "Homepage",
		description: "Generated by create next app",
		images: [
			"https://media.geeksforgeeks.org/wp-content/cdn-uploads/20200214165928/Web-Development-Course-Thumbnail.jpg",
		],
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<NextUILayout>
					<NavbarComponent />
					<ErrorBoundary errorComponent={Error}>
						{children}
					</ErrorBoundary>
				</NextUILayout>
			</body>
		</html>
	);
}
