import CardComponent from "@/components/cards/CardComponent";
import { ProductType } from "@/types/product";
import { Suspense, useEffect } from "react";
import LoadingComponent from "../loading";
import Link from "next/link";
import { Metadata } from "next";

async function fetchProduct() {
	const product = await fetch("https://dummyjson.com/products?limit=100", {
		cache: "no-store",
	});
	const res = await product.json();
	return res.products;
}

export const metadata: Metadata = {
	icons: {
		icon: "/assets/pic.jpg",
	},
	title: "product",
	description: "Generated by create next app",
	keywords : ["NextUI", "React", "Next.js"],
};

export default async function Home() {
	const products = await fetchProduct();

	return (
		<>
			<div className="mt-10 flex justify-center flex-wrap gap-5">
				<Suspense fallback={<LoadingComponent />}>
					{products?.map((pro: ProductType) => {
						return (
							<Link href={`/product/${pro.id}`} key={pro.id}>
								<CardComponent
									thumbnail={pro.thumbnail}
									title={pro.title}
									price={pro.price}
									discountPercentage={pro.discountPercentage}
								/>
							</Link>
						);
					})}
				</Suspense>
			</div>
		</>
	);
}
